export type CategoryListing = {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  rating: number;
  reviewCount: number;
  offerPercent?: number;
  address: string;
  priceLevel?: string;
  tags?: string[];
};

export type CategoryPageContent = {
  title: string;
  subtitle: string;
  description: string;
  listings: CategoryListing[];
};

const UNSPLASH_PARAMS = 'w=900&auto=format&fit=crop';

export const CATEGORY_CONTENT: Record<string, CategoryPageContent> = {
  restaurants: {
    title: 'Restaurants',
    subtitle: 'Citywide dining edits',
    description: 'Trending tables, rooftop sundowners, chef-driven menus and hyperlocal comfort picks updated daily.',
    listings: [
      {
        id: 'restaurants-1',
        name: 'The Urban Tandoor',
        description: 'Modern Indian kitchen with charcoal grills, chef tasting menus and skyline seating.',
        imageUrl: `https://images.unsplash.com/photo-1504674900247-0877df9cc836?${UNSPLASH_PARAMS}`,
        rating: 4.8,
        reviewCount: 368,
        offerPercent: 20,
        address: 'Fraser Road, Patna',
        priceLevel: '₹₹₹',
        tags: ['Fine dining', 'Live music'],
      },
      {
        id: 'restaurants-2',
        name: 'Bao & Biryani Co.',
        description: 'Street-style Asian baos meet slow-cooked biryani bowls and craft coolers.',
        imageUrl: `https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?${UNSPLASH_PARAMS}`,
        rating: 4.4,
        reviewCount: 198,
        offerPercent: 35,
        address: 'Kankarbagh, Patna',
        priceLevel: '₹₹',
        tags: ['Takeaway', 'Trending'],
      },
    ],
  },
  hotels: {
    title: 'Hotels',
    subtitle: 'Staycation staples',
    description: 'Business travel essentials and boutique escapes with effortless check-ins and curated perks.',
    listings: [
      {
        id: 'hotels-1',
        name: 'Aurelia Business Hotel',
        description: 'Smart rooms with city views, rooftop pool and complimentary boardroom access.',
        imageUrl: `https://images.unsplash.com/photo-1501117716987-c8e1ecb210cc?${UNSPLASH_PARAMS}`,
        rating: 4.7,
        reviewCount: 432,
        offerPercent: 30,
        address: 'Exhibition Road, Patna',
        priceLevel: '₹₹₹',
        tags: ['Business', 'Pool'],
      },
      {
        id: 'hotels-2',
        name: 'Casa Verde Suites',
        description: 'Boutique stay with artisanal breakfast, co-working lounge and on-call concierge.',
        imageUrl: `https://images.unsplash.com/photo-1505693314120-0d443867891c?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 219,
        offerPercent: 18,
        address: 'Pataliputra Colony, Patna',
        priceLevel: '₹₹₹',
        tags: ['Boutique', 'Suites'],
      },
    ],
  },
  'beauty-spa': {
    title: 'Beauty & Spa',
    subtitle: 'Glow edit',
    description: 'LED facials, wellness rituals and artisanal beauty bars curated for city downtime.',
    listings: [
      {
        id: 'beauty-1',
        name: 'Glow Studio & Spa',
        description: 'Holistic skin clinic with ayur-glow rituals, LED facials and vegan retail.',
        imageUrl: `https://images.unsplash.com/photo-1501896000177-b6e7dcd5d0db?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 162,
        offerPercent: 25,
        address: 'Buddha Colony, Patna',
        priceLevel: '₹₹',
        tags: ['Skin', 'Vegan'],
      },
      {
        id: 'beauty-2',
        name: 'Bloom Aesthetics Lounge',
        description: 'Premium hair spa, nano extensions and bridal makeover pods.',
        imageUrl: `https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?${UNSPLASH_PARAMS}`,
        rating: 4.8,
        reviewCount: 203,
        offerPercent: 40,
        address: 'Patliputra Kurji, Patna',
        priceLevel: '₹₹₹',
        tags: ['Hair', 'Bridal'],
      },
    ],
  },
  'home-decor': {
    title: 'Home Decor',
    subtitle: 'Spaces refreshed',
    description: 'Studios and ateliers for bespoke furniture, textured walls, lighting and styling.',
    listings: [
      {
        id: 'home-decor-1',
        name: 'Maison Lines Studio',
        description: 'Custom furniture lab with modular lines, recycled teak and fabric library.',
        imageUrl: `https://images.unsplash.com/photo-1505693314120-0d443867891c?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 156,
        offerPercent: 15,
        address: 'Boring Road, Patna',
        priceLevel: '₹₹₹',
        tags: ['Furniture', 'Custom'],
      },
      {
        id: 'home-decor-2',
        name: 'Studio Clay & Cane',
        description: 'Earthy decor edits with ceramics, cane lighting and planters.',
        imageUrl: `https://images.unsplash.com/photo-1505691938895-1758d7feb511?${UNSPLASH_PARAMS}`,
        rating: 4.3,
        reviewCount: 98,
        address: 'Kidwaipuri, Patna',
        priceLevel: '₹₹',
        tags: ['Sustainable', 'Lighting'],
      },
    ],
  },
  'wedding-planning': {
    title: 'Wedding Planners',
    subtitle: 'Celebrations on cue',
    description: 'Concept designers, decor ateliers and hospitality pros crafting immersive weddings.',
    listings: [
      {
        id: 'wedding-1',
        name: 'House of Mendhi',
        description: 'Intimate mehendi & haldi edits with botanical installs and indie artists.',
        imageUrl: `https://images.unsplash.com/photo-1520854223477-8e4385a525b5?${UNSPLASH_PARAMS}`,
        rating: 4.9,
        reviewCount: 245,
        offerPercent: 20,
        address: 'Gola Road, Patna',
        priceLevel: '₹₹₹₹',
        tags: ['Intimate', 'Decor'],
      },
      {
        id: 'wedding-2',
        name: 'Echo Events Co.',
        description: 'Large-format productions, artist bookings and hospitality concierge.',
        imageUrl: `https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 177,
        address: 'Pataliputra, Patna',
        priceLevel: '₹₹₹₹',
        tags: ['Grand', 'Production'],
      },
    ],
  },
  education: {
    title: 'Education',
    subtitle: 'Future-ready labs',
    description: 'Hybrid classrooms, language pods and STEM mentors with real-time progress insights.',
    listings: [
      {
        id: 'education-1',
        name: 'MentorEdge Academy',
        description: 'Hybrid IIT-JEE prep with AI progress coach and immersive doubt rooms.',
        imageUrl: `https://images.unsplash.com/photo-1503676260728-1c00da094a0b?${UNSPLASH_PARAMS}`,
        rating: 4.9,
        reviewCount: 589,
        address: 'Boring Canal Road, Patna',
        priceLevel: '₹₹',
        tags: ['Engineering', 'Hybrid'],
      },
      {
        id: 'education-2',
        name: 'Lingua Pro Studio',
        description: 'IELTS, TOEFL and business communication with micro-batch focus.',
        imageUrl: `https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?${UNSPLASH_PARAMS}`,
        rating: 4.7,
        reviewCount: 174,
        offerPercent: 15,
        address: 'Rajendra Nagar, Patna',
        priceLevel: '₹₹',
        tags: ['Language', 'Soft skills'],
      },
    ],
  },
  'rent-hire': {
    title: 'Rent & Hire',
    subtitle: 'Gear & spaces on demand',
    description: 'Short-term rentals for appliances, workspace pods, décor props and premium fleets.',
    listings: [
      {
        id: 'rent-hire-1',
        name: 'FlexiHome Rentals',
        description: 'Appliance bundles and furnished short-stays with concierge support.',
        imageUrl: `https://images.unsplash.com/photo-1493809842364-78817add7ffb?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 143,
        offerPercent: 25,
        address: 'Kankarbagh, Patna',
        tags: ['Appliances', 'Short stay'],
      },
      {
        id: 'rent-hire-2',
        name: 'DriveMint Fleet',
        description: 'Self-drive SUVs, EV sedans and chauffeur services for events.',
        imageUrl: `https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?${UNSPLASH_PARAMS}`,
        rating: 4.4,
        reviewCount: 189,
        address: 'Bailey Road, Patna',
        tags: ['Cars', 'Events'],
      },
    ],
  },
  hospitals: {
    title: 'Hospitals',
    subtitle: 'Trusted care hubs',
    description: 'Multi-speciality centers, critical care units and preventive health programs.',
    listings: [
      {
        id: 'hospitals-1',
        name: 'Apex Multispeciality',
        description: '24x7 emergency, robotic surgery suites and digital patient lounge.',
        imageUrl: `https://images.unsplash.com/photo-1504439468489-c8920d796a29?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 320,
        address: 'Ashok Rajpath, Patna',
        tags: ['Emergency', 'Robotics'],
      },
      {
        id: 'hospitals-2',
        name: 'Nova Heart & Wellness',
        description: 'Cardiac OT, preventive diagnostics and personalised rehab.',
        imageUrl: `https://images.unsplash.com/photo-1485846234645-a62644f84728?${UNSPLASH_PARAMS}`,
        rating: 4.4,
        reviewCount: 210,
        offerPercent: 10,
        address: 'Boring Road, Patna',
        tags: ['Cardiac', 'Diagnostics'],
      },
    ],
  },
  contractors: {
    title: 'Contractors',
    subtitle: 'Build smart',
    description: 'Turnkey civil teams, modular interiors and maintenance pros vetted for quality.',
    listings: [
      {
        id: 'contractors-1',
        name: 'Gridline Constructions',
        description: 'Residential turnkey builds with BIM tracking and on-site QC.',
        imageUrl: `https://images.unsplash.com/photo-1503387762-592deb58ef4e?${UNSPLASH_PARAMS}`,
        rating: 4.7,
        reviewCount: 140,
        address: 'Rajendra Nagar, Patna',
        tags: ['Turnkey', 'BIM'],
      },
      {
        id: 'contractors-2',
        name: 'CraftHaus Interiors',
        description: 'Design-build interiors, modular kitchens and after-service warranty.',
        imageUrl: `https://images.unsplash.com/photo-1498050108023-c5249f4df085?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 112,
        offerPercent: 12,
        address: 'Patliputra Colony, Patna',
        tags: ['Interiors', 'Warranty'],
      },
    ],
  },
  'pet-shops': {
    title: 'Pet Shops',
    subtitle: 'For the paw squad',
    description: 'Curated nutrition, groomers on call and playful boarding picks.',
    listings: [
      {
        id: 'pet-1',
        name: 'Paw Pantry Collective',
        description: 'Air-dried treats, vet-approved meal plans and subscription boxes.',
        imageUrl: `https://images.unsplash.com/photo-1518378188025-22bd89516ee2?${UNSPLASH_PARAMS}`,
        rating: 4.8,
        reviewCount: 164,
        offerPercent: 20,
        address: 'Sri Krishna Puri, Patna',
        tags: ['Nutrition', 'Subscriptions'],
      },
      {
        id: 'pet-2',
        name: 'Fur & Feather Spa',
        description: 'Hydro baths, creative grooming and weekend boarding.',
        imageUrl: `https://images.unsplash.com/photo-1507146426996-ef05306b995a?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 110,
        address: 'Buddha Colony, Patna',
        tags: ['Grooming', 'Boarding'],
      },
    ],
  },
  'pg-hostels': {
    title: 'PG & Hostels',
    subtitle: 'Move-in ready stays',
    description: 'Managed accommodations with smart security, meals, WiFi and housekeeping.',
    listings: [
      {
        id: 'pg-1',
        name: 'Nest Quarter Living',
        description: 'Private rooms, biometric entry, chef plans and laundry bar.',
        imageUrl: `https://images.unsplash.com/photo-1505691723518-36a5ac3be353?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 205,
        offerPercent: 18,
        address: 'Kankarbagh, Patna',
        tags: ['Premium', 'Meals'],
      },
      {
        id: 'pg-2',
        name: 'StayNova Hostels',
        description: 'Community hostels with coworking lounge, events and fast WiFi.',
        imageUrl: `https://images.unsplash.com/photo-1505691938895-1758d7feb511?${UNSPLASH_PARAMS}`,
        rating: 4.3,
        reviewCount: 150,
        address: 'Patliputra, Patna',
        tags: ['Community', 'Events'],
      },
    ],
  },
  'estate-agent': {
    title: 'Estate Agents',
    subtitle: 'Homes matched better',
    description: 'Smart brokers for rentals, co-living, retail floors and investment plots.',
    listings: [
      {
        id: 'estate-1',
        name: 'Atlas Realty Desk',
        description: 'Data-backed home discovery, legal desk and documentation concierge.',
        imageUrl: `https://images.unsplash.com/photo-1493809842364-78817add7ffb?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 187,
        address: 'Boring Road, Patna',
        tags: ['Buy/Sell', 'Documentation'],
      },
      {
        id: 'estate-2',
        name: 'Retail Grid Advisors',
        description: 'High-street and mall leasing with footfall analytics.',
        imageUrl: `https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?${UNSPLASH_PARAMS}`,
        rating: 4.4,
        reviewCount: 99,
        address: 'Fraser Road, Patna',
        tags: ['Retail', 'Analytics'],
      },
    ],
  },
  dentists: {
    title: 'Dentists',
    subtitle: 'Smiles mapped',
    description: 'Digital smile design, painless root canals and preventive care lounges.',
    listings: [
      {
        id: 'dentist-1',
        name: 'Pearl Align Studio',
        description: 'Clear aligners, smile design preview and sedation dentistry.',
        imageUrl: `https://images.unsplash.com/photo-1527613426441-4da17471b66d?${UNSPLASH_PARAMS}`,
        rating: 4.9,
        reviewCount: 132,
        offerPercent: 15,
        address: 'Boring Road, Patna',
        tags: ['Aligners', 'Cosmetic'],
      },
      {
        id: 'dentist-2',
        name: 'Nova Dental Lounge',
        description: 'Family dentistry, kids zone and emergency response team.',
        imageUrl: `https://images.unsplash.com/photo-1485846234645-a62644f84728?${UNSPLASH_PARAMS}`,
        rating: 4.7,
        reviewCount: 175,
        address: 'Kidwaipuri, Patna',
        tags: ['Family', 'Emergency'],
      },
    ],
  },
  gym: {
    title: 'Gyms',
    subtitle: 'Movement labs',
    description: 'Strength clubs, pilates lofts and metabolic studios with personal coaching.',
    listings: [
      {
        id: 'gym-1',
        name: 'PulseForge Athletics',
        description: 'Strength + conditioning, ice baths, recovery lounge and in-app tracking.',
        imageUrl: `https://images.unsplash.com/photo-1517836357463-d25dfeac3438?${UNSPLASH_PARAMS}`,
        rating: 4.8,
        reviewCount: 220,
        offerPercent: 30,
        address: 'Kidwaipuri, Patna',
        tags: ['Strength', 'Recovery'],
      },
      {
        id: 'gym-2',
        name: 'Studio Vinyasa Lab',
        description: 'Reformer pilates, aerial yoga and breathwork pods.',
        imageUrl: `https://images.unsplash.com/photo-1506126613408-eca07ce68773?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 160,
        address: 'Rajendra Nagar, Patna',
        tags: ['Pilates', 'Yoga'],
      },
    ],
  },
  loans: {
    title: 'Loans',
    subtitle: 'Smart finance desks',
    description: 'Instant approvals for MSME, education and housing finance with transparent fees.',
    listings: [
      {
        id: 'loans-1',
        name: 'CapitalSpring Finance',
        description: 'MSME working capital, invoice discounting and cashflow insights.',
        imageUrl: `https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 145,
        offerPercent: 12,
        address: 'Fraser Road, Patna',
        tags: ['MSME', 'Working capital'],
      },
      {
        id: 'loans-2',
        name: 'EduBridge Finance',
        description: 'Education loans with co-lending partners and zero foreclosure.',
        imageUrl: `https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?${UNSPLASH_PARAMS}&sat=-20`,
        rating: 4.3,
        reviewCount: 120,
        address: 'Buddha Colony, Patna',
        tags: ['Education', 'Zero fees'],
      },
    ],
  },
  'event-organisers': {
    title: 'Event Organisers',
    subtitle: 'Experiences curated',
    description: 'Launches, pop-ups and social gatherings managed end-to-end with creative directors.',
    listings: [
      {
        id: 'events-1',
        name: 'Canvas Affair Studios',
        description: 'Brand launches, immersive pop-ups and design-forward parties.',
        imageUrl: `https://images.unsplash.com/photo-1520854223477-8e4385a525b5?${UNSPLASH_PARAMS}&sat=20`,
        rating: 4.7,
        reviewCount: 134,
        address: 'Exhibition Road, Patna',
        tags: ['Brand', 'Pop-ups'],
      },
      {
        id: 'events-2',
        name: 'Sync Social Co.',
        description: 'Corporate summits, hybrid live streams and hospitality desks.',
        imageUrl: `https://images.unsplash.com/photo-1469474968028-56623f02e42e?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 118,
        offerPercent: 22,
        address: 'Bailey Road, Patna',
        tags: ['Corporate', 'Hybrid'],
      },
    ],
  },
  'driving-schools': {
    title: 'Driving Schools',
    subtitle: 'On-road confidence',
    description: 'Dual-control fleets, simulator drills and RTO concierge in one place.',
    listings: [
      {
        id: 'drive-1',
        name: 'SteerSmart Academy',
        description: 'Automated lesson plans, night-drive coaching and assessment reports.',
        imageUrl: `https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?${UNSPLASH_PARAMS}&sat=-10`,
        rating: 4.6,
        reviewCount: 190,
        address: 'Kankarbagh, Patna',
        tags: ['Simulator', 'Night drives'],
      },
      {
        id: 'drive-2',
        name: 'Ignition Pro School',
        description: 'Compact + SUV coaching, licence paperwork and refresher courses.',
        imageUrl: `https://images.unsplash.com/photo-1517940310602-285a6c62b30a?${UNSPLASH_PARAMS}`,
        rating: 4.4,
        reviewCount: 150,
        offerPercent: 18,
        address: 'Ashiana-Digha Road, Patna',
        tags: ['Paperwork', 'Refresher'],
      },
    ],
  },
  'packers-movers': {
    title: 'Packers & Movers',
    subtitle: 'Moves made simple',
    description: 'City and intercity relocations with smart inventory tracking and insurance.',
    listings: [
      {
        id: 'packers-1',
        name: 'Lift & Shift Logistics',
        description: 'Full-service relocations with IoT trackers and damage cover.',
        imageUrl: `https://images.unsplash.com/photo-1541971875078-7c5c8a2360dd?${UNSPLASH_PARAMS}`,
        rating: 4.5,
        reviewCount: 210,
        offerPercent: 20,
        address: 'Gardanibagh, Patna',
        tags: ['Intercity', 'Insurance'],
      },
      {
        id: 'packers-2',
        name: 'UrbanPack Crew',
        description: 'Studio moves, eco packing material and express unpack services.',
        imageUrl: `https://images.unsplash.com/photo-1473186505569-9c61870c11f9?${UNSPLASH_PARAMS}`,
        rating: 4.3,
        reviewCount: 150,
        address: 'Pataliputra, Patna',
        tags: ['Eco', 'Express'],
      },
    ],
  },
  'courier-service': {
    title: 'Courier Service',
    subtitle: 'Same-day circuits',
    description: 'Hyperlocal deliveries, B2B logistics and subscription pickups on tap.',
    listings: [
      {
        id: 'courier-1',
        name: 'SwiftParcel Express',
        description: 'Same-day intra-city with live tracking dashboards.',
        imageUrl: `https://images.unsplash.com/photo-1515165562835-c4c1bfa67a47?${UNSPLASH_PARAMS}`,
        rating: 4.6,
        reviewCount: 175,
        offerPercent: 15,
        address: 'Kidwaipuri, Patna',
        tags: ['Same-day', 'Tracking'],
      },
      {
        id: 'courier-2',
        name: 'CargoLoop Logistics',
        description: 'B2B line-hauls, cold chain and international document runs.',
        imageUrl: `https://images.unsplash.com/photo-1434575472303-3625a83fbd0c?${UNSPLASH_PARAMS}`,
        rating: 4.4,
        reviewCount: 120,
        address: 'Exhibition Road, Patna',
        tags: ['B2B', 'Cold chain'],
      },
    ],
  },
};

export const getCategoryContent = (key: string) => CATEGORY_CONTENT[key];

